"""add documents table

Revision ID: 87b583e2328a
Revises: c598ee24cd04
Create Date: 2026-04-14 15:03:58.689312

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '87b583e2328a'
down_revision = 'c598ee24cd04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
