"""initial

Revision ID: c598ee24cd04
Revises: 
Create Date: 2026-04-14 14:57:10.200669

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = 'c598ee24cd04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
